name: Face Shape API Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.FACE_EC2_HOST }}
          EC2_USERNAME: ${{ secrets.FACE_EC2_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.FACE_SSH_PRIVATE_KEY }}

        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 400 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USERNAME@$EC2_HOST << 'EOF'
            set -e

            echo "Pulling latest changes from GitHub..."
            cd ~/Face-Shape-Detection-Model
            git pull origin main

            echo "Installing dependencies..."
            source ~/venv/bin/activate
            pip install -r requirements.txt

            echo "Restarting Gunicorn..."
            sudo systemctl restart faceshape.service
            echo "Deployment completed successfully."
          EOF

          rm key.pem
